import os
pairs_keys = [('features.0.weight', 'down1.conv1.cbr_unit.0.weight'),
 ('features.0.bias', 'down1.conv1.cbr_unit.0.bias'),
 ('features.1.weight', 'down1.conv1.cbr_unit.1.weight'),
 ('features.1.bias', 'down1.conv1.cbr_unit.1.bias'),
 ('features.1.running_mean', 'down1.conv1.cbr_unit.1.running_mean'),
 ('features.1.running_var', 'down1.conv1.cbr_unit.1.running_var'),
 ('features.3.weight', 'down1.conv2.cbr_unit.0.weight'),
 ('features.3.bias', 'down1.conv2.cbr_unit.0.bias'),
 ('features.4.weight', 'down1.conv2.cbr_unit.1.weight'),
 ('features.4.bias', 'down1.conv2.cbr_unit.1.bias'),
 ('features.4.running_mean', 'down1.conv2.cbr_unit.1.running_mean'),
 ('features.4.running_var', 'down1.conv2.cbr_unit.1.running_var'),

 ('features.7.weight', 'down2.conv1.cbr_unit.0.weight'),
 ('features.7.bias', 'down2.conv1.cbr_unit.0.bias'),
 ('features.8.weight', 'down2.conv1.cbr_unit.1.weight'),
 ('features.8.bias', 'down2.conv1.cbr_unit.1.bias'),
 ('features.8.running_mean', 'down2.conv1.cbr_unit.1.running_mean'),
 ('features.8.running_var', 'down2.conv1.cbr_unit.1.running_var'),
 ('features.10.weight', 'down2.conv2.cbr_unit.0.weight'),
 ('features.10.bias', 'down2.conv2.cbr_unit.0.bias'),
 ('features.11.weight', 'down2.conv2.cbr_unit.1.weight'),
 ('features.11.bias', 'down2.conv2.cbr_unit.1.bias'),
 ('features.11.running_mean', 'down2.conv2.cbr_unit.1.running_mean'),
 ('features.11.running_var', 'down2.conv2.cbr_unit.1.running_var'),

 ('features.14.weight', 'down3.conv1.cbr_unit.0.weight'),
 ('features.14.bias', 'down3.conv1.cbr_unit.0.bias'),
 ('features.15.weight', 'down3.conv1.cbr_unit.1.weight'),
 ('features.15.bias', 'down3.conv1.cbr_unit.1.bias'),
 ('features.15.running_mean', 'down3.conv1.cbr_unit.1.running_mean'),
 ('features.15.running_var', 'down3.conv1.cbr_unit.1.running_var'),
 ('features.17.weight', 'down3.conv2.cbr_unit.0.weight'),
 ('features.17.bias', 'down3.conv2.cbr_unit.0.bias'),
 ('features.18.weight', 'down3.conv2.cbr_unit.1.weight'),
 ('features.18.bias', 'down3.conv2.cbr_unit.1.bias'),
 ('features.18.running_mean', 'down3.conv2.cbr_unit.1.running_mean'),
 ('features.18.running_var', 'down3.conv2.cbr_unit.1.running_var'),
 ('features.20.weight', 'down3.conv3.cbr_unit.0.weight'),
 ('features.20.bias', 'down3.conv3.cbr_unit.0.bias'),
 ('features.21.weight', 'down3.conv3.cbr_unit.1.weight'),
 ('features.21.bias', 'down3.conv3.cbr_unit.1.bias'),
 ('features.21.running_mean', 'down3.conv3.cbr_unit.1.running_mean'),
 ('features.21.running_var', 'down3.conv3.cbr_unit.1.running_var'),

 ('features.24.weight', 'down4.conv1.cbr_unit.0.weight'),
 ('features.24.bias', 'down4.conv1.cbr_unit.0.bias'),
 ('features.25.weight', 'down4.conv1.cbr_unit.1.weight'),
 ('features.25.bias', 'down4.conv1.cbr_unit.1.bias'),
 ('features.25.running_mean', 'down4.conv1.cbr_unit.1.running_mean'),
 ('features.25.running_var', 'down4.conv1.cbr_unit.1.running_var'),
 ('features.27.weight', 'down4.conv2.cbr_unit.0.weight'),
 ('features.27.bias', 'down4.conv2.cbr_unit.0.bias'),
 ('features.28.weight', 'down4.conv2.cbr_unit.1.weight'),
 ('features.28.bias', 'down4.conv2.cbr_unit.1.bias'),
 ('features.28.running_mean', 'down4.conv2.cbr_unit.1.running_mean'),
 ('features.28.running_var', 'down4.conv2.cbr_unit.1.running_var'),
 ('features.30.weight', 'down4.conv3.cbr_unit.0.weight'),
 ('features.30.bias', 'down4.conv3.cbr_unit.0.bias'),
 ('features.31.weight', 'down4.conv3.cbr_unit.1.weight'),
 ('features.31.bias', 'down4.conv3.cbr_unit.1.bias'),
 ('features.31.running_mean', 'down4.conv3.cbr_unit.1.running_mean'),
 ('features.31.running_var', 'down4.conv3.cbr_unit.1.running_var'),

 ('features.34.weight', 'down5.conv1.cbr_unit.0.weight'),
 ('features.34.bias', 'down5.conv1.cbr_unit.0.bias'),
 ('features.35.weight', 'down5.conv1.cbr_unit.1.weight'),
 ('features.35.bias', 'down5.conv1.cbr_unit.1.bias'),
 ('features.35.running_mean', 'down5.conv1.cbr_unit.1.running_mean'),
 ('features.35.running_var', 'down5.conv1.cbr_unit.1.running_var'),
 ('features.37.weight', 'down5.conv2.cbr_unit.0.weight'),
 ('features.37.bias', 'down5.conv2.cbr_unit.0.bias'),
 ('features.38.weight', 'down5.conv2.cbr_unit.1.weight'),
 ('features.38.bias', 'down5.conv2.cbr_unit.1.bias'),
 ('features.38.running_mean', 'down5.conv2.cbr_unit.1.running_mean'),
 ('features.38.running_var', 'down5.conv2.cbr_unit.1.running_var'),
 ('features.40.weight', 'down5.conv3.cbr_unit.0.weight'),
 ('features.40.bias', 'down5.conv3.cbr_unit.0.bias'),
 ('features.41.weight', 'down5.conv3.cbr_unit.1.weight'),
 ('features.41.bias', 'down5.conv3.cbr_unit.1.bias'),
 ('features.41.running_mean', 'down5.conv3.cbr_unit.1.running_mean'),
 ('features.41.running_var', 'down5.conv3.cbr_unit.1.running_var')]



if __name__=='__main__':
    print(len(pairs_keys))
    for p in pairs_keys:
        print(p)